name: Deploy MkDocs to GitHub Pages

on:
    push:
        branches: [main]
    workflow_dispatch:

# Needed so mkdocs gh-deploy can push to the gh-pages branch
permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # 1) Checkout the public repo with the default GITHUB_TOKEN
            #    (DON'T use your PAT here, we want pushes to use GITHUB_TOKEN)
            - name: Checkout (repo only)
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: false
                  persist-credentials: true

            # 2) Pull the private submodule using your fine-grained PAT (read-only)
            - name: Fetch private submodules
              run: |
                  git submodule sync --recursive
                  # Use the PAT only for this command via a temporary header
                  git -c http.https://github.com/.extraheader="AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.VAULT_PAT }} | base64)" \
                    submodule update --init --recursive --depth=1

            # 3) Python + deps
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - name: Install MkDocs and dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install \
                    mkdocs-material \
                    mkdocs-roamlinks-plugin \
                    mkdocs-blog-plugin \
                    mkdocs-rss-plugin \
                    pymdown-extensions

            # 4) Build and push to gh-pages using the default GITHUB_TOKEN
            - name: Deploy to GitHub Pages (gh-pages branch)
              env:
                  GIT_AUTHOR_NAME: github-actions
                  GIT_AUTHOR_EMAIL: github-actions@github.com
                  GIT_COMMITTER_NAME: github-actions
                  GIT_COMMITTER_EMAIL: github-actions@github.com
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  mkdocs gh-deploy --clean --force --strict
